name: Organize Words by First Letter

on:
  schedule:
    - cron: '0 16 * * *' # 每天零点执行
  workflow_dispatch:

jobs:
  organize-words:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PyYAML
      run: |
        python -m pip install pyyaml

    - name: Run organize words script
      run: |
        python organize_words.py

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add word
        timestamp=$(date -u)
        git commit -m "Update organized words - $timestamp"
        git push
